{
 "title": "Coordinated recovery",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Reactor metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "reactor util",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(vectorized_reactor_utilization{instance=~\".*\",shard=~\".*\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pending tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(vectorized_reactor_tasks_pending{instance=~\".*\",shard=~\".*\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "io queue length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(vectorized_io_queue_queue_length{instance=~\".*\",shard=~\".*\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "task quota violation ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(vectorized_scheduler_time_spent_on_task_quota_violations_ms{instance=~\".*\",shard=~\".*\"}[6s])) by (instance)/1000/4",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Internal RPC metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "internal rpc client sent bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(vectorized_rpc_client_in_bytes{}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "internal rpc server recv bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(vectorized_internal_rpc_received_bytes{}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "internal rpc latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(vectorized_internal_rpc_latency_bucket{instance=~\".*\",shard=~\".*\"}[6s])) by (le, instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "internal rpc pending requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(vectorized_internal_rpc_requests_pending{instance=~\".*\",shard=~\".*\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raft-level metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true
  },
  {
   "title": "Partitions to recover/Partitions active",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(vectorized_raft_recovery_partitions_to_recover{instance=~\".*\",shard=~\".*\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(vectorized_raft_recovery_partitions_active{instance=~\".*\",shard=~\".*\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "leadership changes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(vectorized_raft_leadership_changes{instance=~\".*\",shard=~\".*\"}[6s])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offsets to recover",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(vectorized_raft_recovery_offsets_pending{instance=~\".*\",shard=~\".*\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sent vote requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(vectorized_raft_sent_vote_requests{}[6s])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "recovery requests sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(rate(vectorized_raft_recovery_requests{}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "leader step downs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum(rate(vectorized_raft_step_downs{instance=~\".*\",shard=~\".*\"}[6s])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "recovery request errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(rate(vectorized_raft_recovery_requests_errors{}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "leader balancer transfers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "sum(irate(vectorized_leader_balancer_leader_transfer_succeeded{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true
  },
  {
   "title": "kafka produce latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(vectorized_kafka_handler_latency_microseconds_bucket{handler=\"produce\", instance=~\".*\",shard=~\".*\"}[6s])) by (le, instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka metadata requests completed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(vectorized_kafka_handler_requests_completed_total{handler=\"metadata\"}[6s])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka produce received bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(vectorized_kafka_handler_received_bytes_total{handler=\"produce\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka metadata sent bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(vectorized_kafka_handler_sent_bytes_total{handler=\"metadata\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka produce errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum(rate(vectorized_kafka_handler_requests_errored_total{handler=\"produce\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}